//original code follows

//let day = Wednesday;
//console.log(day;

//My guesses at correct syntax are:
//let day = "Wednesday";
//console.log(day);

//Chapter 6 asks what error messages were generated by running the original code

//The error messages were:

//Uncaught SyntaxError C:\Users\i-swa\Documents\LaunchCode\javascript-projects\errors-and-debugging\chapter-examples\SyntaxErrors.js:2
//console.log(day;
//    ^^^
//
//SyntaxError: missing ) after argument list
//at internalCompileFunction (node:internal/vm:77:18)
//at wrapSafe (node:internal/modules/cjs/loader:1288:20)
//at Module._compile (node:internal/modules/cjs/loader:1340:27)
//at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
//at Module.load (node:internal/modules/cjs/loader:1207:32)
//at Module._load (node:internal/modules/cjs/loader:1023:12)
//at executeUserEntryPoint (node:internal/modules/run_main:135:12)
//at <anonymous> (node:internal/main/run_main_module:28:49)
//Process exited with code 1

//Trying my guesses:

let day = "Wednesday";
console.log(day);